### ISSUE TITLE
wrong use of pragma(inline)

### ISSUE THREAD

**Issue by WebFreak001** [aquaratixc/redo-d#1]
The `pragma(inline, true);` (note the trailing semicolon) does not have any effect, that pragma actually works more like an attribute you need to directly attach to a function or use with `{}` or `:`

Issue in https://github.com/aquaratixc/redo-d/blob/3772019ec12aa1c32c2c62a638d85ff807ad043c/redo.d#L42

See https://godbolt.org/z/x98c38Yox

**Comment by aquaratixc** [comment]
Thanks. Thank you for such a valuable comment.  I forgot to remove the unnecessary pragma from the final version, the pragma is now removed
